hex1 = 0xDEADBEEF
hex2 = 0xdeadbeef
hex3 = 0xdead_beef
hex0 = 0x0
hex_leading_zero = 0x000001
oct1 = 0o01234567
oct2 = 0o755
bin1 = 0b11010110
sf1 = inf
sf2 = +inf
sf3 = -inf
sf4 = nan
sf6 = +nan
sf5 = -nan
